# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: dev

  dev:
    cmds:
      - hugo serve --disableFastRender

  publish:
    cmds:
      - hugo

  theme:
    cmds:
      - git submodule add https://github.com/dillonzq/LoveIt.git themes/LoveIt
      