# https://taskfile.dev

version: '3'

includes:
  automation: tools/taskfiles/automation.taskfile.yml
  blog: tools/taskfiles/blog.taskfile.yml
  
  hugo: tools/taskfiles/lib/hugo.taskfile.yml
  devenv: tools/taskfiles/lib/devenv.taskfile.yml
  direnv: tools/taskfiles/lib/direnv.taskfile.yml
  magick: tools/taskfiles/lib/magick.taskfile.yml
  

tasks:
  default:  
    - task: hugo